thrusters:
  ym:
    position: [0, -0.175, 0]
    directions: [[1.0, 0.0, 0.0], [-1.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, 0.0, -1.0]]
    max_force: 1.0
  yp:
    position: [0, 0.175, 0]
    directions: [[1.0, 0.0, 0.0], [-1.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, 0.0, -1.0]]
    max_force: 1.0
  xp:
    position: [0.175, 0, 0]
    directions: [[0.0, 1.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0, 1.0], [0.0, 0.0, -1.0]]
    max_force: 1.0
  xm:
    position: [-0.175, 0, 0]
    directions: [[0.0, 1.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0, 1.0], [0.0, 0.0, -1.0]]
    max_force: 1.0